name: Mirror Repositories Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - 'repos_to_mirror.yml'

jobs:
  process_project_additions:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_MIRROR_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Process Project Additions
        run: python process_additions.py
      
      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add repos_to_mirror.yml
          if [ -f added_projects.txt ]; then
            PROJECT_NAMES=$(cat added_projects.txt | tr '\n' ' ' | sed 's/ $//')
            COMMIT_MESSAGE="Update repos_to_mirror.yml with new project additions: $PROJECT_NAMES"
          else
            COMMIT_MESSAGE="Update repos_to_mirror.yml with new project additions"
          fi
          git status
          if [ -n "$(git status --porcelain)" ]; then
            # Checkout to a new branch based on the latest state of the target branch
            git fetch origin feature/first-impl
            git checkout -b temp-branch-for-changes origin/feature/first-impl
            git commit -m "$COMMIT_MESSAGE"
            # Optional: Handle potential merge conflicts here
            git push origin temp-branch-for-changes:feature/first-impl
          else
            echo "No changes to commit"
          fi
          rm -f added_projects.txt  # Clean up the temporary file



  mirror_repositories:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Mirror Repositories
        run: python mirror_repos_from_global.py
